=== IGSN/csiro-igsn-schema/3.0/igsn-csiro-v3.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2016 rel. 2 (x64) (http://www.altova.com) by Anu (Personal) -->
<xs:schema xmlns:cs="https://igsn.csiro.au/schemas/3.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink/namespace" xmlns:igsn="http://igsn.org/schema/kernel-v.1.0" targetNamespace="https://igsn.csiro.au/schemas/3.0" elementFormDefault="qualified" version="2.0">
	<xs:import namespace="http://igsn.org/schema/kernel-v.1.0" schemaLocation="include/igsn-dateType.xsd"/>
	<xs:import namespace="http://igsn.org/schema/kernel-v.1.0" schemaLocation="include/igsn-nameIdentifierScheme-v1.0.xsd"/>
	<xs:import namespace="http://igsn.org/schema/kernel-v.1.0" schemaLocation="include/igsn-identifierType-v1.0.xsd"/>
	<xs:import namespace="http://igsn.org/schema/kernel-v.1.0" schemaLocation="include/igsn-eventType-v1.0.xsd"/>
	<xs:import namespace="http://igsn.org/schema/kernel-v.1.0" schemaLocation="include/igsn-dateType.xsd"/>
	<xs:include schemaLocation="include/sampleType.xsd"/>
	<xs:include schemaLocation="include/samplingFeature.xsd"/>
	<xs:include schemaLocation="include/materialType.xsd"/>
	<xs:include schemaLocation="include/spatialType.xsd"/>
	<xs:include schemaLocation="include/nillType.xsd"/>
	<!-- xs:import namespace="http://www.opengis.net/gml/3.2" schemaLocation="http://schemas.opengis.net/gml/3.2.1/basicTypes.xsd"/ -->
	<!-- xs:import namespace="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3.org/2001/XMLSchema-instance"/ -->
	<xs:element name="samples">
		<xs:annotation>
			<xs:documentation>A batch of sample resouces that will registered with IGSNs. </xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<!--xs:element name="subNamespace" minOccurs="1" maxOccurs="1">
					<xs:annotation>
						<xs:documentation>The subnamespace of the data center registering the samples</xs:documentation>
					</xs:annotation>
				</xs:element -->
				<xs:element name="sample" minOccurs="1" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>A 'sample' may be an individual specimen or a collection (e.g., a collection may be formed when a number of arbitrary specimens grouped together or it may be an aggregation of samples with material relations) </xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:all>
							<xs:element name="sampleIdentifier">
								<xs:annotation>
									<xs:documentation>(Required)The first two characters must be [A-Z] and represents the namespace of an allocating agent, e.g, CS is assigned to CSIRO. This is followed by 3 characters [A-Z] representing the client, as assigned by the respective allocating agent. The rest is the local sample code designated by the client. The rest can be a combination of characters, numbers and dash (-) and dot(.).</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="cs:igsnSyntax">
											<xs:attribute name="identifierType" type="igsn:identifierType" use="required"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
							<!-- sample number, e.g., igsn -->
							<xs:element name="sampleName">
								<xs:annotation>
									<xs:documentation>The name of the sample.</xs:documentation>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:token">
										<xs:minLength value="1"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="otherNames" minOccurs="0">
								<xs:annotation>
									<xs:documentation>An alias for the sample name. Use this element to include local name/identifier of the sample.</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element name="otherName" maxOccurs="unbounded">
											<xs:simpleType>
												<xs:restriction base="xs:token">
													<xs:minLength value="1"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="isPublic">
								<xs:annotation>
									<xs:documentation>The visibility of a sample metadata. Use 1 for public and 0 for private samples.</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:boolean"/>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
							<xs:element name="landingPage">
								<xs:annotation>
									<xs:documentation>The landing page of a sample.</xs:documentation>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:anyURI">
										<xs:pattern value="https?://.+"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="sampleTypes" nillable="true">
								<xs:annotation>
									<xs:documentation>The basic form of a sample, e.g. core, cuttings and grab. See controlled list "include/sampleType.xsd". If the value of a sampleType is not available, declare the xsi:nil and nilReason attributes, e.g.,  xsi:nil="true" nilReason="http://www.opengis.net/def/nil/OGC/0/missing"</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element name="sampleType" type="cs:sampleType" maxOccurs="unbounded"/>
									</xs:sequence>
									<xs:attributeGroup ref="cs:nilReasonType"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="materialTypes" nillable="true">
								<xs:annotation>
									<xs:documentation>The materials that compose a sample, e.g., rock, sediment, and soil. See controlled list "include/materialType.xsd"</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element name="materialType" type="cs:materialType" maxOccurs="unbounded"/>
									</xs:sequence>
									<xs:attributeGroup ref="cs:nilReasonType"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="classification" minOccurs="0">
								<xs:annotation>
									<xs:documentation>Classification concepts, e.g. Rock>Igneous.Use the classifictionIdentifier attibute to indicate the URI of the concept.</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:token">
											<xs:attribute name="classificationIdentifier" type="xs:anyURI"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
							<xs:element name="purpose" minOccurs="0">
								<xs:annotation>
									<xs:documentation>The purpose for collecting the sample.</xs:documentation>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:token">
										<xs:minLength value="1"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="samplingLocation" nillable="true">
								<xs:annotation>
									<xs:documentation>The location where the sample is collected. This may refer to geo (latlon,localxy, bounding box(bbox)) and non-geo(locality) location. Example of latitude and longitude: 51.150719,-0.973177. Example of localxy (UTM Easting and UTM Northing) is : 641753.82,5668538.64. The srs attribute can be used to indicate the UTMZone (e.g., 30U) or SRID. If the location value is not available, declare the xsi:nil and nilReason attributes.</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:group ref="cs:locationGroup">
										<xs:annotation>
											<xs:documentation>
			</xs:documentation>
										</xs:annotation>
									</xs:group>
									<xs:attributeGroup ref="cs:nilReasonType"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="samplingTime" nillable="true">
								<xs:annotation>
									<xs:documentation>The temporal information of sample collection. </xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:group ref="cs:timeGroup"/>
									<xs:attributeGroup ref="cs:nilReasonType"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="sampledFeatures" nillable="true">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="sampledFeature" maxOccurs="unbounded">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:token">
														<xs:attribute name="sampledFeatureType" type="xs:anyURI"/>
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attributeGroup ref="cs:nilReasonType"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="samplingFeature" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="samplingFeatureName">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute name="samplingFeatureType" type="cs:samplingFeature"/>
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
										<xs:element name="samplingFeatureLocation" minOccurs="0">
											<xs:annotation>
												<xs:documentation>The location of a sampling feature. This may apply to geo (specified in WKT format) and non-geo (locality) information. The 'srs' attribute can be used to indicate the  Spatial Reference System Identifier (SRID).</xs:documentation>
											</xs:annotation>
											<xs:complexType>
												<xs:group ref="cs:locationGroup">
													<xs:annotation>
														<xs:documentation>		</xs:documentation>
													</xs:annotation>
												</xs:group>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="sampleCollectors" nillable="true">
								<xs:annotation>
									<xs:documentation>Contact information of the person who collected the sample.This also applies to the principal investigator in a project responsible for sample collection.</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element name="collector" maxOccurs="unbounded">
											<!--xs:complexType>
												<xs:simpleContent>
													<xs:extension base="igsn:StringOrNillValues">
														<xs:attribute name="collectorIdentifier" type="xs:anyURI" use="optional"/>
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType -->
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:token">
														<xs:attribute name="collectorIdentifier" type="xs:anyURI" use="optional"/>
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attributeGroup ref="cs:nilReasonType"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="samplingMethod" nillable="true">
								<xs:annotation>
									<xs:documentation>Method/equipment used to collect the sample, e.g., Dredging, Manual Observation. </xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:token">
											<xs:attributeGroup ref="cs:nilReasonType"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
							<xs:element name="samplingCampaign" minOccurs="0">
								<xs:annotation>
									<xs:documentation>The field program/related projects.  e.g., cruise or expedition.</xs:documentation>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:token">
										<xs:minLength value="1"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="sampleCuration" nillable="false">
								<xs:annotation>
									<xs:documentation>Sample archival information. The curator information must be specified. This can be present or future curator.</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element name="curation" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="curator" type="xs:token"/>
													<xs:element name="curationTime" minOccurs="0">
														<xs:annotation>
															<xs:documentation>The temporal information of sample curation</xs:documentation>
														</xs:annotation>
														<xs:complexType>
															<xs:group ref="cs:timeGroup"/>
														</xs:complexType>
													</xs:element>
													<xs:element name="curationLocation" type="xs:token" minOccurs="0"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="comments" minOccurs="0">
								<xs:annotation>
									<xs:documentation>Any free text describing the sample. This also can be used to include additional metadata which cannot be specified with this standard schema.</xs:documentation>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:token">
										<xs:minLength value="1"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="logElement" nillable="false" minOccurs="1" maxOccurs="1">
								<xs:annotation>
									<xs:documentation>Use this element to indicate the status of physical sample and IGSN registration</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:token">
											<xs:attribute name="event" type="igsn:eventType" use="required"/>
											<xs:attribute name="timeStamp" type="igsn:W3CDTFdate" use="required"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:all>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:group name="timeGroup">
		<xs:annotation>
			<xs:documentation>Represents time instant or time period (start,end).</xs:documentation>
		</xs:annotation>
		<xs:all>
			<xs:element name="timeInstant" type="igsn:W3CDTFdate" minOccurs="0" maxOccurs="1"/>
			<xs:element name="timePeriod" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="start" type="igsn:W3CDTFdate" minOccurs="0"/>
						<xs:element name="end" type="igsn:W3CDTFdate" minOccurs="0"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:all>
	</xs:group>
	<xs:group name="locationGroup">
		<xs:annotation>
			<xs:documentation>This may apply to a named place (locality) or geometric (coordinate-based) location, e.g., WKT representation. The srs attribute indicates a Spatial Reference System Identifier (SRID), e.g., EPSG:4326
			</xs:documentation>
		</xs:annotation>
		<xs:all>
			<xs:element name="locality" type="xs:token" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Named place or address</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="wkt" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Well Known Text (wkt) representation of entity. </xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string">
							<xs:attribute name="srid" type="xs:token" use="required">
								<xs:annotation>
									<xs:documentation>Use EPSG code (http://www.epsg-registry.org/), e.g., "EPSG:XXX", where "XXX" is the EPSG code for the referenced coordinate system; "none" shall be provided if the coordinate system is unreferenced.</xs:documentation>
								</xs:annotation>
							</xs:attribute>
							<xs:attribute name="spatialType" type="cs:spatialType" use="required"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="elevation" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Height of an entity above datum.</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string">
							<xs:attribute name="datum" type="xs:token" use="optional">
								<xs:annotation>
									<xs:documentation>a vertical datums specify the origin for elevations assocated with a feature, e.g., MSL, NAVD88, NGVD29, or Unknown</xs:documentation>
								</xs:annotation>
							</xs:attribute>
							<xs:attribute name="units" type="xs:token" use="optional"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
		</xs:all>
	</xs:group>
	<xs:attributeGroup name="nilReasonType">
		<xs:attribute name="nilReason" type="cs:NilReasonType" use="optional"/>
	</xs:attributeGroup>
	<xs:simpleType name="igsnSyntax">
		<xs:annotation>
			<xs:documentation>IGSN syntax data type</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:token">
			<xs:pattern value="([A-Z]{2}[A-Za-z0-9\-.]+)"/>
		</xs:restriction>
	</xs:simpleType>
	<!--- xs:simpleType name="trueOrFalse">
		<xs:restriction base="xs:boolean">
			<xs:pattern value="0"/>
			<xs:pattern value="1"/>
		</xs:restriction>
	</xs:simpleType -->
	<!--xs:simpleType name="StringOrNillValues">
		<xs:union memberTypes="xs:anyURI igsn:NilReasonType"/>
	</xs:simpleType -->
</xs:schema>

=== IGSN/csiro-igsn-schema/3.0/example-subcollection.xml
<?xml version="1.0" encoding="UTF-8"?>
<cs:samples xmlns:cs="https://igsn.csiro.au/schemas/3.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://igsn.csiro.au/schemas/3.0 igsn-csiro-v3.0.xsd">
	<cs:sample>
		<cs:sampleIdentifier identifierType="igsn">CSRWASC00630</cs:sampleIdentifier>
		<cs:sampleName>SC00630</cs:sampleName>
		<cs:isPublic>false</cs:isPublic>
		<cs:landingPage>https://rockstore.csiro.au/arrc/#/browsesubcollections/CSRWASC00630</cs:landingPage>
		<cs:sampleTypes xsi:nil="true" nilReason="http://www.opengis.net/def/nil/OGC/0/missing"/>
		<cs:materialTypes>
			<cs:materialType>http://vocabulary.odm2.org/medium/rock</cs:materialType>
		</cs:materialTypes>
		<cs:samplingLocation xsi:nil="true" nilReason="http://www.opengis.net/def/nil/OGC/0/missing"/>
		<cs:samplingTime xsi:nil="true" nilReason="http://www.opengis.net/def/nil/OGC/0/missing"/>
		<cs:sampledFeatures xsi:nil="true" nilReason="http://www.opengis.net/def/nil/OGC/0/missing"/>
		<cs:sampleCollectors xsi:nil="true" nilReason="http://www.opengis.net/def/nil/OGC/0/missing"/>
		<cs:samplingMethod xsi:nil="true" nilReason="http://www.opengis.net/def/nil/OGC/0/missing"/>
		<cs:sampleCuration>
			<cs:curation>
				<cs:curator>CSIRO</cs:curator>
				<cs:curationLocation>G9-L1, RockStore, 7 Conlon Street,Waterford WA 6152</cs:curationLocation>
			</cs:curation>
		</cs:sampleCuration>
		<cs:logElement event="submitted" timeStamp="2015-08-17T09:32:00"/>
	</cs:sample>
</cs:samples>
